spring.application.name=train-service

server.port=8082

spring.datasource.url=jdbc:mysql://localhost:3306/railway_reservation_system
spring.datasource.username=root
spring.datasource.password=ubuntu

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

jwt.secret=mysecretkeymysecretkeymysecretkey
jwt.expiration=3600000

spring.autoconfigure.exclude=org.springframework.boot.security.autoconfigure.UserDetailsServiceAutoConfiguration